name: Deploy Static App to Amplify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Amplify deployment
        env:
          AMPLIFY_WEBHOOK: ${{ secrets.AMPLIFY_WEBHOOK }}
        run: |
          echo "Triggering Amplify deployment..."
          curl -X POST -d {} "https://webhooks.amplify.eu-north-1.amazonaws.com/prod/webhooks?id=c13c3fb1-76a8-42d8-bc43-95977bd6a1d7&token=ibiEMfaL1eNNwhczrJTYp6r1R3i59ciHy7FuzNKps&operation=startbuild" -H "Content-Type:application/json"
